version: '3'

services:

  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: micro-api-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts: 
      - "host.docker.internal:172.17.0.1"